// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfBudgetplanerare.Data;

#nullable disable

namespace WpfBudgetplanerare.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260122160509_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfBudgetplanerare.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Housing"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Transportation"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Entertainment"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Utilities"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Salery"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Gift"
                        });
                });

            modelBuilder.Entity("WpfBudgetplanerare.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpenseId = -1,
                            Amount = 1500m,
                            CategoryId = 1,
                            ExpenseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceType = 1
                        },
                        new
                        {
                            ExpenseId = -2,
                            Amount = 300m,
                            CategoryId = 2,
                            ExpenseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceType = 1
                        });
                });

            modelBuilder.Entity("WpfBudgetplanerare.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("int");

                    b.HasKey("IncomeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Incomes");

                    b.HasData(
                        new
                        {
                            IncomeId = -1,
                            Amount = 5000m,
                            CategoryId = 6,
                            ReceivedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceType = 1
                        },
                        new
                        {
                            IncomeId = -2,
                            Amount = 200m,
                            CategoryId = 7,
                            ReceivedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceType = 0
                        });
                });

            modelBuilder.Entity("WpfBudgetplanerare.Models.Expense", b =>
                {
                    b.HasOne("WpfBudgetplanerare.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WpfBudgetplanerare.Models.Income", b =>
                {
                    b.HasOne("WpfBudgetplanerare.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
